apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container.backapp.name }}-service
  namespace: devops
  labels:
    app: {{ .Values.container.backapp.name }}
spec:
  ports:
  - port: {{ .Values.container.backapp.port }}
    protocol: TCP
  selector:
    app: {{ .Values.container.backapp.name }}
  type: {{ .Values.container.backapp.type }}
