apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container.reactapp.name }}-service
  namespace: devops
  labels:
    app: {{ .Values.container.reactapp.name }}
spec:
  ports:
  - port: {{ .Values.container.reactapp.port }}
    protocol: TCP
  selector:
    app: {{ .Values.container.reactapp.name }}
  type: {{ .Values.container.reactapp.type }}
